version: 2.1
orbs:
  node: circleci/node@1.1
jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - run:
          command: npm install
          name: Run npm install
      - run:
          command: npm run lint
          name: Run npm ESLINT
      - run:
          command: npm test
          name: Run npm test
